name: steerkep-env
channels:
  - nvidia
  - pytorch
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - pytorch
  - torchvision
  - torchaudio
  - pytorch-cuda=12.1
  - numpy<2
  - open3d==0.16.0
  - omegaconf
  - opencv-python
  - hydra-core
  - openai
  - torch
  - kmeans_pytorch
  - parse
  - pip
  - pip:
      - omnigibson
